sylius_twig_hooks:
  hooks:
    # Sylius 2.x (placement officiel)
    'sylius_shop.homepage.index#content':
      hero_section:
        template: 'hook/sylius/shop/homepage/hero.html.twig'
        priority: 50

    # Alias historique (certaines installs l'affichent encore dans le profiler)
    'sylius.shop.homepage.content':
      hero_section:
        template: 'hook/sylius/shop/homepage/hero.html.twig'
        priority: 50
